baseURL = "https://jensmaes.be/"
languageCode = "be-nl"
title = "Jens Maes"
theme="archie"
copyright = "© Jens Maes"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="toggle"
	useCDN=false
	subtitle = "A PowerShell-enthousiastic network- and system-administrator living in Mechelen, Belgium."
	favicon = "img/favicon.ico"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/insert-waffle"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/ikbenjensniet"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/jensmaes7/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4